<?php
///////////////////////// DNA Sequencer Module  /////////////////////////
// This module takes a user input string (composed of A,C,T, and G),
// and prints out a diagram of DNA pairs

/////////////////////////// Menu Hook ///////////////////////////

    function dna_sequencer_menu() {
      // Create two pages, one for the form and one for the results
    }



/////////////////////////// Form Hook ///////////////////////////

    function dna_sequencer_form() {
      // Create a form to enter a string ot process into a dna diagram
    }

    function dna_sequencer_form_submit() {
      // On form submit action, process info, store in session, and redirect to results page
    }


/////////////////////////// Form Validators ///////////////////////////





/////////////////////////// DNA Sequencer Logic ///////////////////////////

    // Turns an array of uppercase letters (A,C,T,and G) and turns it
    // into an array containing DNA pairs, in the format "X-X"
    function dna_sequencer_pair_generator($input_array) {

        foreach ($input_array as $index => $character) {
            if (strtoupper($character) === "A") {
                $input_array[$index] = "A-T";
            }
            if (strtoupper($character) === "T") {
                $input_array[$index] = "T-A";
            }
            if (strtoupper($character) === "C") {
                $input_array[$index] = "C-G";
            }
            if (strtoupper($character) === "G") {
                $input_array[$index] = "G-C";
            }
        }

        return $input_array;
    }

    // Turns an array of pairs in the format "x-x" into an unordered
    // list for display
    function dna_sequencer_pair_display($input_array) {

    }

    // Takes a validated string input from the form and returns an html string for display
    function dna_sequencer_sequence($input_string) {

    }

////////////////////////////// Page Callback //////////////////////////////

    function dna_sequencer_result() {

    }
