<?php
///////////////////////// DNA Sequencer Module  /////////////////////////
// This module takes a user input string (composed of A,C,T, and G),
// and prints out a diagram of DNA pairs

/////////////////////////// Menu Hook ///////////////////////////

    function dna_sequencer_menu()
    {
        // Create two pages, one for the form and one for the results
        $items['dna_sequencer_input'] = array(
            'title' => 'DNA Sequence Creator',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('dna_sequencer_form'),
            'access callback' => true,
            'type' => MENU_NORMAL_ITEM,
        );
        $items['dna_sequencer_result'] = array(
            'title' => 'DNA Sequencer Results',
            'page callback' => 'dna_sequencer_result',
            'access callback' => true,
            'type' => MENU_CALLBACK,
        );

        return $items;
    }

/////////////////////////// Form Hook ///////////////////////////

    function dna_sequencer_form()
    {
        // Create a form to enter a string ot process into a dna diagram
        $form['dna'] = array(
            '#type' => 'fieldset',
            '#title' => t('Create a DNA string'),
        );
        $form['dna']['sequence'] = array(
            '#type' => 'textfield',
            '#title' => 'Sequence',
            '#description' => t('Enter a string comprised of the letters A,C,T, and G.'),
            '#required' => true,
        );
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Sequence DNA!',
            '#validate' => array('dna_sequencer_form_validate'),
        );

        return $form;
    }

    function dna_sequencer_form_submit($form, &$form_state)
    {
        // On form submit, clean up input (to upper case and string to array)
        $input_as_array = str_split($form_state['values']['sequence']);

        // Run functions to convert to double helix format, and then to
        // convert to displayable string with html
        $pairs = dna_sequencer_pair_generator($input_as_array);
        $output = dna_sequencer_pair_display($pairs);

        // Store the output in session so it is available for display on the results page
        $_SESSION['dna_sequencer_result'] = $output;

        // Redirect to display page
        $form_state['redirect'] = 'dna_sequencer_result';
    }

/////////////////////////// Form Validators ///////////////////////////

    function dna_sequencer_form_validate()
    {

    }

/////////////////////////// DNA Sequencer Logic ///////////////////////////

    // Turns an array of uppercase letters (A,C,T,and G) and turns it
    // into an array containing DNA pairs, in the format "X-X"
    function dna_sequencer_pair_generator($input_array)
    {
        foreach ($input_array as $index => $character) {
            if (strtoupper($character) === 'A') {
                $input_array[$index] = 'A-T';
            }
            if (strtoupper($character) === 'T') {
                $input_array[$index] = 'T-A';
            }
            if (strtoupper($character) === 'C') {
                $input_array[$index] = 'C-G';
            }
            if (strtoupper($character) === 'G') {
                $input_array[$index] = 'G-C';
            }
        }

        return $input_array;
    }

    // Turns an array of pairs in the format "x-x" into an unordered
    // list for display
    function dna_sequencer_pair_display($input_array)
    {
        $result = '<ul>';
        foreach ($input_array as $dna_pair) {
            $result .= '<li>'.$dna_pair.'</li>';
        }
        $result .= '</ul>';

        return $result;
    }

////////////////////////////// Page Callback //////////////////////////////

    function dna_sequencer_result()
    {
        return $_SESSION['dna_sequencer_result'];
    }
